### ISSUE TITLE
Can't create a migration

### ISSUE THREAD

**Issue by linkys** [deliciousbrains/wp-migrate-db#101]
I created a new migration. After I tried to create another one, but got next error:

[Table '_mig_wpmdb_alter_statements' already exists]
CREATE TABLE `_mig_wpmdb_alter_statements` ( `query` LONGTEXT NOT NULL )

{"migration_state_id":"5cfe583705fef"}

I suppose the plugin doesn't check if table is exists. What do you think?

**Comment by dahousecat** [comment]
I just tried to drop table table manually and got the error DROP command denied.

So I suspect that neither you are I have drop permission granted to the mysql user that our wordpress sites are using. Adding this permission should fix the problem.

**Comment by kevinwhoffman** [comment]
Hi there, I'm just following up on old issues. If this is still a problem with the latest version of WP Migrate DB 2.2.1, then please reopen and we can take another look.
