### ISSUE TITLE
Isn't compatible with Master Slider

### ISSUE THREAD

**Issue by cyphix333** [deliciousbrains/wp-migrate-db#104]
I am using Master Slider: https://wordpress.org/plugins/master-slider/

However it seems it doesn't search/replace the contents of "text layers" created with Master Slider.

**Comment by cyphix333** [comment]
Does anyone maintain this? Just found out it also doesn't replace text within the Oshine themes custom CSS.

Guess I'll have to find another tool after using this for a long time.

**Comment by cyphix333** [comment]
@kevinwhoffman Why was this closed?

**Comment by kevinwhoffman** [comment]
@cyphix333 Hi there, I'm the new product manager for WP Migrate DB, and I was reviewing older issues to see if we could bring our backlog up to date. If you are using WP Migrate DB 2.2.1 and having an issue with the Find & Replace tool, then please reopen and let me know the plugin versions that you have installed with steps to recreate the issue. I will be happy to take a closer look.
