### ISSUE TITLE
Do not remove excluded post type, just not alter them

### ISSUE THREAD

**Issue by romainarchimbaud** [deliciousbrains/wp-migrate-db#105]
Hi there,
I'm new to github so I hope I'm in the right place to explain my issues.

Is it possible when you exclude a post_type for a pull/push to not remove it from the wp table?
What I want in fact is, from my local environnement I got a new blog post and also I'm still working on a page update. I want to push my blog post on the production website but excluding the post_type "Page".
Actually if I exclude my "Page" post_type, all those post_type are remove.
And what I want is just to not alter them. 
Maybe there is some hook to tweak with?
Regards

**Comment by kevinwhoffman** [comment]
Hi, I know this is an old issue, but I wanted to follow up and clarify that a push/pull migration involves the complete replacement of database tables. So when you choose to exclude a post type, that data is left out of the migration completely. When the tables are replaced on the destination site, there will be no entries for that post type.

At this time, there is no way to exclude individual posts.
