### ISSUE TITLE
Function get_magic_quotes_gpc() is deprecated when using PHP 7.4

### ISSUE THREAD

**Issue by trajche** [deliciousbrains/wp-migrate-db#108]
```
Function get_magic_quotes_gpc() is deprecated in /home/brandsgateway/webapps/brandsgateway/wp-content/plugins/wp-migrate-db-pro/class/Common/FormData/FormData.php on line 93
```

This is happening with WP_DEBUG enabled as a warning, while using CLI migration on WP Migrate DB Pro with PHP version 7.4.

**Comment by kevinwhoffman** [comment]
Closing as this warning was resolved several releases ago:
https://github.com/deliciousbrains/wp-migrate-db/blob/346c56d588cfeb8ed8a52d3b16e50dd6f2bbd283/readme.txt#L247-L248
