### ISSUE TITLE
Use WP Migrate DB  to migrate mu-plugins

### ISSUE THREAD

**Issue by carlotrimarchi** [deliciousbrains/wp-migrate-db#111]
Hello,
I would like to be able to migrate the content of the `mu-plugins` directory using WP Migrate DB.
I'm not sure if this is already possible, but I tried searching through the docs and here and couldn't find anything.

As it's considered a good practice, I normally create my `Custom Post Types` in the `mu-plugins` directory, but having to rely on other ways of uploading them to a remote website is kind of annoying. Since the plugin is already able to sync plugins, which live outside the theme directory, shouldn't it be possible to do the same for mu-plugins?

**Comment by RichardTMiles** [comment]
This probably deserves its own thread, but is there cli options for plugins? I'd like to download them too

**Comment by polevaultweb** [comment]
@RichardTMiles CLI commands for migrating [Themes & Plugin Files](https://deliciousbrains.com/wp-migrate-db-pro/#addons) is coming soon, and is available if you are a license holder on the current beta release

**Comment by RichardTMiles** [comment]
@polevaultweb How would I access this feature? I download the pro version via composer so possibly the version number and cli flag I need to add would be extremely helpful.

**Comment by RichardTMiles** [comment]
I've kept an eye on the website and seen no updates to as to the specifics of this feature :/

**Comment by polevaultweb** [comment]
hey @RichardTMiles the beta version isn't available via Composer at the moment, however you can update the plugin and addons to the beta versions via Tools > Migrate DB Pro > Settings with the 'Beta Version Updates' setting. Once turned on, you should see updates available for the plugins.

**Comment by carlotrimarchi** [comment]
@RichardTMiles @polevaultweb, is this discussion related at all to the main question?

**Comment by polevaultweb** [comment]
@carlotrimarchi No it isn't.

Regarding migrating mu-plugins, it's been raised on our issue tracker and we've added your vote to it.

**Comment by carlotrimarchi** [comment]
@polevaultweb thanks! Any way I can follow the issue?

**Comment by polevaultweb** [comment]
@carlotrimarchi you can sign up to hear product updates via the form at the bottom of https://deliciousbrains.com/wp-migrate-db-pro/

**Comment by RichardTMiles** [comment]
@polevaultweb I'm a pro user, how do I know when the composer repo has been updated? Is there a readme somewhere?
