### ISSUE TITLE
Stored procedures not exported

### ISSUE THREAD

**Issue by Infotaku** [deliciousbrains/wp-migrate-db#112]
Hi,

One of our internal plugins is using stored procedures and migrate DB is not exporting them.
Is this the expected behaviour or I am not aware of some config option I should enable ?

Thank you for your time !

**Comment by polevaultweb** [comment]
Hi @Infotaku, WP Migrate DB and the Pro version will only migrate tables as part of the database migration - it doesn't migrate views or stored procedures. However, I'll log your request and add your vote to it 👍
