### ISSUE TITLE
License field not appearing

### ISSUE THREAD

**Issue by indaviande** [deliciousbrains/wp-migrate-db#115]
I've just updated from v1.9.14 to v2.0 (by downloading the V2 extension on the wordpress marketplace, because the V2 wasn't pushed automatically).
And I can't input my license field (no fields in settings). Thus, impossible to do my migrations

[localhost-diagnostic-log-20210428132442.txt](https://github.com/deliciousbrains/wp-migrate-db/files/6392079/localhost-diagnostic-log-20210428132442.txt)

**Comment by mattgrshaw** [comment]
Hi @indaviande, it looks like you have the free version installed. That version won't have the license key or the ability to run push/pull migrations.

You can download the pro version from the "My Account" section on our site:
https://deliciousbrains.com/signin/

Can you please clarify what you mean by v2 not being pushed automatically? Were you not seeing the update for it in the WordPress dashboard? Usually if that happens, going to the WordPress Dashboard -> Updates, and then clicking "Check Again" will get the updates to show up.

**Comment by indaviande** [comment]
In Extensions, I couldn't get any messages saying there was an update. Maybe because it's localhost (I had the update message on a remote server).
But you're right, going to Dashbord > Updates & Check again, pushed me the update.

It's all good now.
