### ISSUE TITLE
installs on older version and stops working

### ISSUE THREAD

**Issue by fxrsliberty** [deliciousbrains/wp-migrate-db#117]
it appears that there is no minimum version checking during install. it simply installs and causes the CLI to fail with an error about the profile being from an older version... 
I did a simple plugin update on this version of WordPress, 5.1.2 because is said it was available....
"WP Migrate DB Pro 2.0.2 is now available. You currently have 1.9.8 installed. Update Now"
there is no way to downgrade and the location of the profiles seems to be a "State Secret" so i'm having to quess my way back to working because I didn't back up my dev machine and it looks like the profiles don't process with the migration.....

**Comment by kevinwhoffman** [comment]
Hi there, I know it's been a while but I wanted to follow up to let you know that migration profiles are stored in the `wp_options` table with an `option_name` of `wpmdb_saved_profiles`. I hope that you were able to recreate your migration profile. Please reopen if you need help.
