### ISSUE TITLE
Error: ReferenceError: Can't find variable: ResizeObserver

### ISSUE THREAD

**Issue by evandrolamaral** [deliciousbrains/wp-migrate-db#119]
When I choose: "+ New Migration", I have this error, and don't open a dialog for migration:

Oops! An error occured!
Here’s what we know…
Error: ReferenceError: Can't find variable: ResizeObserver
Stacktrace: in si in div in Unknown in f in no in Po in Do in t in div in div in t in styled.div in div in t in es in div in t in styled.div in t in t in py in t

My diagnostics info here:

I remove this variables for secure:
site_url():  
home_url():  
Database Name:  

Table Prefix:   wpxs_
WordPress Version:  5.7.2
WP Migrate DB:  2.0.1
Web Server: ..................... LiteSpeed
PHP: ............................ 7.4.16
WP Memory Limit: ................ 40M
PHP Time Limit: ................. 90
Blocked External HTTP Requests:   None
fsockopen: ...................... Enabled
OpenSSL: ........................ OpenSSL 1.1.1d  10 Sep 2019
cURL: ........................... Enabled
Enable SSL verification setting:  No
Opcache Enabled: ................ Enabled
MySQL: ................... 10.3.29-MariaDB
ext/mysqli: .............. yes
WP Locale: ............... pt_BR
DB Charset: .............. utf8
WPMDB_STRIP_INVALID_TEXT:  No
Debug Mode: ... No
Debug Log: .... No
Debug Display:  Yes
Script Debug:   No
PHP Error Log:  error_log
WP Max Upload Size:  8 MB
PHP Post Max Size:   8 MB
WPMDB Bottleneck: ...... 8 MB
Compatibility Mode: .... Yes
Delay Between Requests:  0
WP_HOME: ....... Not defined
WP_SITEURL: .... Not defined

---> I remove this variables for secure:
WP_CONTENT_URL:  
WP_CONTENT_DIR: 
WP_PLUGIN_DIR:  
WP_PLUGIN_URL:   
Active Theme Name:    Futurio
Active Theme Folder: 

Active Plugins
 -  All-in-One WP Migration (v7.43) by ServMask
 -  Classic Editor (v1.6) by WordPress Contributors
 -  Contact Form 7 (v5.4.1) by Takayuki Miyoshi
 -  Duplicate Page (v4.4) by mndpsingh287
 -  Elementor Pro (v2.9.4) by Elementor.com
 -  Elementor (v3.0.5) by Elementor.com
 -  Futurio Extra (v1.5.0) by FuturioWP
 -  LiteSpeed Cache (v3.6.4) by LiteSpeed Technologies
 -  Page Links To (v3.3.5) by Mark Jaquith
 -  PDF Image Generator (v1.5.6) by Mizuho Ogino
 -  Post Category Prev-Next Link Fix (v1.0) by Ketan Ambaliya
 -  Regenerate Thumbnails (v3.1.5) by Alex Mills (Viper007Bond)
 -  Manutenção Site (v2.4.0) by Designmodo
 -  WP Migrate DB (v2.0.1) by Delicious Brains
 -  WPDM - Gutenberg Blocks (v2.0.7) by WordPress Download Manager
 -  WP Synchro (v1.6.4) by WPSynchro

Must-Use Plugins
 -  WP Migrate DB Compatibility (v1.2) by Delicious Brains
 -  WP Synchro MU plugin (v1.0.3) by WP Synchro

**Comment by AhmedTheGeek** [comment]
@evandrolamaral Can you give us more information about what browser are you using, and what version is it?

**Comment by evandrolamaral** [comment]
Hi,

I'm using Safari 13.05 on my Macbook, MacOS 10.15.03, but now I'm run in Chrome and works great...

**Comment by AhmedTheGeek** [comment]
@evandrolamaral Looks like ResizeObserver support was added to Safari since 13.4, so 13.05 wouldn't have had it yet. 

We can show an appropriate message for unsupported browsers to avoid such vague errors, I'll add an issue for that.

Thanks for reporting the error.

**Comment by kevinwhoffman** [comment]
ResizeObserver should now be [supported in Safari](https://caniuse.com/resizeobserver), so I'm going to close this out. Thanks!
