### ISSUE TITLE
How do I install wp-migrate-db-pro plugin via CLI?

### ISSUE THREAD

**Issue by hectoralicea** [deliciousbrains/wp-migrate-db#122]
Simple question, that I'm having difficulty finding how to do it.

I'm trying to setup an init container script that installs and configures and runs wp-migrate-db-pro CLI to import a database pre-stored in GIT.

When I try I get the following:
```
$ wp plugin install wp-migrate-db-pro --activate
Warning: wp-migrate-db-pro: Plugin not found.
Warning: The 'wp-migrate-db-pro' plugin could not be found.
Error: No plugins installed.
```
I am able to install the free version
```
$ wp plugin install wp-migrate-db --activate
Warning: wp-migrate-db: Plugin already installed.
Activating 'wp-migrate-db'...
Warning: Plugin 'wp-migrate-db' is already active.
Success: Plugin already installed.
```

I presume I should be able to run some sort of cli command that would allow me to download and install the plugin, pass the software key as a parameter then activate it.

Any help would be appreciated.

**Comment by kevinwhoffman** [comment]
Hi there, I know it's been a while but I wanted to let you know that you can [install WP Migrate DB Pro via Composer](https://deliciousbrains.com/wp-migrate-db-pro/doc/installing-via-composer/). This is the best route if you want to handle the installation and activation of the plugin from the CLI.
