### ISSUE TITLE
The Export migration failed during the Table Migration stage.

### ISSUE THREAD

**Issue by elias161** [deliciousbrains/wp-migrate-db#123]
Hola, tengo problemas al intentar usar WP migrate Db, al empezar a correr se detiene en 1% y sale este error:
The Export migration failed during the Table Migration stage. luego se detiene . help !
![2021-08-10_14-53-03](https://user-images.githubusercontent.com/88741705/128926278-5b856254-db01-43e9-9905-0aafce6e1441.png)

**Comment by kevinwhoffman** [comment]
Hi there, if you're still experiencing this issue, please reopen with more detail about the error, which you can gather from: `Tools > Migrate DB Pro > Help> Diagnostic Info & Error Log`
