### ISSUE TITLE
Migrating MediaFiles Extremely slow after update 2.x

### ISSUE THREAD

**Issue by pietgeluk** [deliciousbrains/wp-migrate-db#126]
This has been bothering me for a while now. After updating to 2.x everything runs smoothly except migrating the mediafiles. Somehow this takes forever, sometime over 1 hour if the website has quite a few files.

But even 3GB takes over 20 minutes. 
Our server is top notch and this hasn't been a problem with version 1.x.

Is there a fix or explanation for this? 
Thanks in advance.

![Schermafbeelding-2021-10-13-om-11 15 16](https://user-images.githubusercontent.com/56450884/137106071-a7e16081-82d8-415b-b878-83defc2fd50e.jpg)

**Comment by polevaultweb** [comment]
Can you just confirm what versions of the Pro and Media Files plugin you are running?

**Comment by pietgeluk** [comment]
Hi @polevaultweb, I haven't heard from u in a even sinds your last message. This problem still occurs, hope to hear from u.

**Comment by polevaultweb** [comment]
Hey @pietgeluk, can you go increase the 'Maximum Request Size' slider in the plugin's settings (Tools > Migrate DB Pro > Settings)

![Screen Shot 2021-11-03 at 12 08 05 PM](https://user-images.githubusercontent.com/1770201/140050336-0f9e5c6a-9098-4c8b-a924-db19528c23a3.png)

We are looking to improve that setting to be more reactive to the connection limits, to make it as automatically quick as possible.

**Comment by pietgeluk** [comment]
Thanks @polevaultweb, this sure helps.
It's still slower than before but takes the edge off! 

Thanks!
