### ISSUE TITLE
Find & replace doesn't work in latest update

### ISSUE THREAD

**Issue by ts-mz** [deliciousbrains/wp-migrate-db#127]
Hi,

in case I'm not the only one for whom this is happening:

I've been trying it a number of times, but the find & replace feature doesn't work in the latest update (free version) on a new local installation of WP (PHP 7.3.5). There is no indication of an error, but not a single URL is being replaced in the exported db file. After reverting to an older version everything went smoothly again.

**Comment by kevinwhoffman** [comment]
Hi there, if you're still experiencing this issue, please reopen with the information requested above.
