### ISSUE TITLE
From V2.4.2 - Uncaught TypeError: array_intersect(): Argument #1 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by f-liva** [deliciousbrains/wp-migrate-db#142]
![image](https://user-images.githubusercontent.com/346224/202233957-09e3fe32-9678-4b03-a504-11973bdea627.png)

**Comment by f-liva** [comment]
A simple cast will fix the problem

![image](https://user-images.githubusercontent.com/346224/202237244-6c2caefc-2998-4262-93c1-994b5b9f6e08.png)

**Comment by philwp** [comment]
@f-liva thanks for raising this issue. We are already aware of this and have a fix that is already merged in the upcoming 2.5.0 release.
