### ISSUE TITLE
New update gives "Unable to determine folder name for theme Array Wordpress" failure

### ISSUE THREAD

**Issue by dennisjonda** [deliciousbrains/wp-migrate-db#144]
I tried to create a migration with several sites, but everywhere I get the same error message: "Unable to determine folder name for theme Array Wordpress".

With the older versions the migration works.

**Comment by AhmedTheGeek** [comment]
Hi @dennisjonda, are you using a custom `themes` directory? or a custom `wp-content` path?

**Comment by WihlkeJulius** [comment]
I got the same problem when running `wp migratedb profile 1 --path=/home/website/public_html/`
It's a plain WordPress install with a child theme.

**Comment by philwp** [comment]
Version 2.6.1 fixed the issue with the file paths when using CLI.
