### ISSUE TITLE
Duplicate records on export

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-migrate-db#5]
Reported via email:

Had another bug today where 3 record were duplicated on export (making the import to another server fail).  I tracked it down to these 3 rows:

`INSERT INTO `wp_commentmeta` VALUES (26288, 8600, 'akismet_result', 'true') ; 
INSERT INTO `wp_commentmeta` VALUES (26289, 8600, 'akismet_history', 'a:4:{s:4:"time";s:15:"1351940104.4301";s:7:"message";s:35:"Akismet caught this comment as spam";s:5:"event";s:10:"check-spam";s:4:"user";s:0:"";}') ; 
INSERT INTO `wp_commentmeta` VALUES (26290, 8600, 'akismet_as_submitted', 'a:64:{s:15:"comment_post_ID";s:4:"2283";s:14:"comment_author";s:22:"Online blackjack guide";s:20:"comment_author_email";s:21:"vbsacpjyzx@dkfrqp.com";s:18:"comment_author_url";s:21:"http://linea-pro.com/";s:15:"comment_content";s:1261:"dbcuhibsujod, <a href="http://linea-pro.com/">Online blackjack no download</a>, YEJZsWM, [url=http://linea-pro.com/]Online blackjack websites[/url], ENuJKpQ, http://linea-pro.com/ Online blackjack strategy card, qOwQEdR, <a href="http://www.coloradoenvision.com/">Priligy t</a>, KSSYWVt, [url=http://www.coloradoenvision.com/]Priligy[/url], Isxdqkw, http://www.coloradoenvision.com/ Buy Priligy, nKzOGZh, <a href="http://ppiclaimsfaq.co.uk/">PPI Claims</a>, UARyXrR, [url=http://ppiclaimsfaq.co.uk/]Claim back ppi charges[/url], izRDhDc, http://ppiclaimsfaq.co.uk/ First plus ppi claims, YPGbaSx, <a href="http://me5168.com/">Jcpenney engagement rings</a>, nmINfHq, [url=http://me5168.com/]Pendant engagement rings princess cut diamond solitaire[/url], lOiLXQo, http://me5168.com/ Engagement rings wholesale, QVEnPVh, <a href="http://pashakentlands.com/">Nu skin 180 system</a>, rSOHYCB, [url=http://pashakentlands.com/]Nu Skin 180[/url], FgOrxIv, http://pashakentlands.com/ Nu skin 180 system with galvanic, wuUdIKx, <a href="http://vokrugsvetanaveslah.com/vpn-service/">Best Vpn Service</a>, rkOFSZB, [url=http://vokrugsvetanaveslah.com/vpn-service/]Vpn Service Reviews[/url], WcLujVY, http://vokrugsvetanaveslah.com/vpn-service/ What Is Vpn Service,`

You can see we had a lot of pending akismet spam, and for some reason db migrate couldn't handle all those records.

Is there any way to troubleshoot this to find out how it made 3 duplicate records in the export file?  My colleagues are concerned this could happen in the future.

**Comment by cih997** [comment]
I've just got 20+ duplicated records in database size ~500MB. Version wp-migrate-db 1.0.1, WordPress 4.8.1. These records are not duplicated in the source database so definitely something wrong with the plugin :/ It's about wp_options table if that helps. Cannot share source DB unfortunately.
