### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tobiasschutter** [deliciousbrains/wp-migrate-db#52]
He Brad, I found a small typo in your pugin.

"Save the above settings for the next time you do a similiar migration"

similiar -> similar

**Comment by darrendyy** [comment]
ok thx bro






Sent from Windows Mail





From: Tobias Schutter
Sent: ‎Friday‎, ‎July‎ ‎31‎, ‎2015 ‎10‎:‎27‎ ‎PM
To: deliciousbrains/wp-migrate-db





He Brad, I found a small typo in your pugin.

"Save the above settings for the next time you do a similiar migration"

similiar -> similar

**Comment by mattgrshaw** [comment]
Thanks for the heads up on this, it will be fixed in the next release.
