### ISSUE TITLE
Always getting a #123 or #129 error

### ISSUE THREAD

**Issue by BobWassermann** [deliciousbrains/wp-migrate-db#54]
Hi,

I've been using the plug-in on a lot of projects lately, but for some reason it doesn't work in my current one.

If I try to push from my local environment to the live site I get the #123 error, after the migration is almost done.
![Error #123](http://i.imgur.com/8nUWgB7.png)

If I try to do it the other way around, pulling from my local environment, I get the #129 error, just after connecting before a modal even opened.
![Error #129](http://i.imgur.com/jMoWcKR.png)

Tried resetting the API key multiple times and read all the issues on this page too. Sadly nothing helped.

Am I overseeing something?

**Comment by bradt** [comment]
@BobWassermann Can you submit your support request through the Help tab in the plugin? Thanks.

**Comment by BobWassermann** [comment]
@bradt *Please report bugs or ask questions in the GitHub Issue Tracker* redirects me to https://github.com/wp-sync-db/wp-sync-db/issues, where I submitted this post

**Comment by bradt** [comment]
Ah, sounds like you're using [WP Sync DB](https://github.com/wp-sync-db/wp-sync-db) which is an out-of-date copy of WP Migrate DB Pro (our paid plugin) that a jerk has released on GitHub for free.

I suggest that you remove it and install the latest release of WP Migrate DB (free version) or buy a WP Migrate DB Pro license. The differences between the free and paid versions are described at the end of the video here: https://wordpress.org/plugins/wp-migrate-db/.

**Comment by BobWassermann** [comment]
Aaah, thanks @bradt, good to know.
