### ISSUE TITLE
Response: (#112) since updating to 0.9.1

### ISSUE THREAD

**Issue by Hlsgs** [deliciousbrains/wp-migrate-db#66]
As in the title, regardless of whether i also upgrade to WP 4.7 or not.
This is on multiple installs and verified on PHP 5.3, 5.4, 5.6 and 7 both on a WAMP stack and in a Vagrant VM.

**Comment by blueocto** [comment]
I also get this error after upgrading to WP 4.7 ;

_A problem occurred when attempting to connect to the local server, please check the details and try again. — Status: 500 Internal Server Error

Response:
(#112)_

**Comment by Hlsgs** [comment]
@blueocto I get it regardless of upgrading to WP 4.7 or not. Simply updating to wp-migrate-db 0.9.1 is enough, regardless of WP version.

**Comment by Hlsgs** [comment]
I can confirm that 0.9.2 fixes this. Closed.
