### ISSUE TITLE
Development and staging URL get listed in my license overview

### ISSUE THREAD

**Issue by wgroenewold** [deliciousbrains/wp-migrate-db#73]
My staging and  development URL are listed in my license overview, thereby limiting the amount of websites I can activate the pro license on. Is it possible to make a field where I can set these URLs so they get excluded from the license count? An other way would be making a UID on every install and thereby recognizing the double sites.

**Comment by ptasker** [comment]
Hi there, it sounds like you have a WP Migrate DB Pro license. Could you please send us a note at priority-wpmdb@deliciousbrains.com and we'll take a look for you?
