### ISSUE TITLE
Find & Replace gets over-zealous with wp_blogs domains

### ISSUE THREAD

**Issue by mlowens** [deliciousbrains/wp-migrate-db#80]
I was searching for "https://mydomain.com" and replacing it with "https://www.mydomain.com" and everything would have worked as planned except that I'm using multisite with subdomains.

In the "wp_blogs" table, the "domain" column values in wp_blogs were updated like this:

www.mydomain.com
subdomain1.www.mydomain.com
subdomain2.www.mydomain.com
subdomain3.www.mydomain.com

The first replace was correct, but obviously the "www." did not belong in any of the subdomains. It's an easy workaround once you know what happened, but it took a bit to track it down.

Ideally, the script would be less zealous. As a developer, my expectation was that it would only match the exact string, so it was surprising to find it was ignoring the "https://" in this instance.

Alternately, a checkbox under Advanced Options to "Exclude wp_blogs table" could be a workable solution. It would at least alert people to where the script might be looking for a non-exact match in the case of the wp_blogs table.

**Comment by JRGould** [comment]
subdomain replacement is a feature of WP Migrate DB Pro that allows you to successfully migrate a subdomain multisite install without having to add find/replace options for each subsite's subdomain. You can turn it off by returning false to the `wpmdb_subdomain_replace` filter on the site running the migration.
