### ISSUE TITLE
wp-cli migrate command 

### ISSUE THREAD

**Issue by raptor235** [deliciousbrains/wp-migrate-db#84]
Is it possible to request a feature for wpi cli to migrate without profiles... profiles can change and it's not safe to assume that every 1st profile is going to do a pull from prod as an example...

Would be nice to be able to specify a key and do a pull and that's it db migrate pro would figure out the paths and domains to replace by itself.

**Comment by mattgrshaw** [comment]
It's already possible to push/pull the database with the push/pull subcommands:
https://deliciousbrains.com/wp-migrate-db-pro/doc/cli-push-pull-subcommand/

You'll just need to define the search/replace fields manually.

**Comment by raptor235** [comment]
Yes I know... this is why I opened the ticket... the fields get defined automatically when you do it via the UI so why wouldn't this be the case when doing the same things via CLI?
