### ISSUE TITLE
No way to activate license

### ISSUE THREAD

**Issue by kleinjm** [deliciousbrains/wp-migrate-db#86]
Reading [these docs](https://deliciousbrains.com/wp-migrate-db-pro/doc/activating-license/), I have no idea where to activate the license in the settings tab. I was also unable to make it work with the env var.

"Enter your license into the text field toward the bottom of the page"

![image](https://user-images.githubusercontent.com/2565158/33245752-db7e8936-d2d9-11e7-9b72-9e0923a6fde2.png)

**Comment by mattgrshaw** [comment]
Replied via email.
