### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by YuvrajKhavad** [deliciousbrains/wp-migrate-db#90]
Hello Team @deliciousbrains,

Nice plugin very easy migrate database.

But there is some time problem in migration. Please check attached screenshot.  

"A problem occurred when attempting to process the following table (#113) bq_duplicator_packages
Status: 500 Internal Server Error

Response:"

![failed migrate db hotelschiff stinne wordpress](https://user-images.githubusercontent.com/2893666/39228003-686415b8-4879-11e8-85c8-74cc439c0f0e.png)

When we installed old migrate db then this problem will fixed.

Thanks in advance.
Yuvraj

**Comment by Rubenxfd** [comment]
I'm having the same problem, any updates?

**Comment by zkingdesign** [comment]
Having the same issues, used this plugin on a bunch of times and now all of the sudden it ain't working.

**Comment by YuvrajKhavad** [comment]
Hello @zkingdesign and @Rubenxfd 

For temporary solutions just installed slow version plugin and migrate the database.

Thank You
Have a great day.

**Comment by rtenny** [comment]
With version 2.6.0 this issue still exist
